- name: Install MySQL
  yum:
    name: '{{ item }}'
    state: latest
  loop: '{{ mysql_modules }}'

- name: Set MySQL root passwd
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present

- name: Create DB WordPress
  mysql_db:
    name: '{{ mysql_db }}'
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'

- name: Create MySQL user WordPress
  mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_password }}'
    priv: '{{ mysql_db }}.*:ALL'
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'
